# Publishing workflow

name: Tag Publish

# Use more columns for terminal output
env:
  COLUMNS: 120
  PYTHONIOENCODING: utf8
  
# trigger the publishing of the 
# gatorgrade package to PyPI
# with any tag starting with 'v'
on:
  push:
    tags:
      - 'v*'
      
# Create one single job
# that publishes the package
# to PyPI using uv

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --dev
      - name: Build package
        run: uv build
      - name: Publish package to PyPI
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      - name: Check for Successful Publication
        run: |
          version=$(uv version --short || grep -oP 'version = "\K[^"]+' pyproject.toml)
          echo "Checking if package gatorgrade version $version is available on PyPI..."
          sleep 10
          response=$(curl -s "https://pypi.org/pypi/gatorgrade/$version/json")
          if echo "$response" | grep -q "$version"; then
            echo "Package gatorgrade version $version is successfully published on PyPI."
          else
            echo "Package gatorgrade version $version was not found on PyPI."
            exit 1
          fi