# Test Publishing workflow
name: Test Publish

# Use more columns for terminal output
env:
  COLUMNS: 120
  PYTHONIOENCODING: utf8
  
# trigger the test publishing of the 
# gatorgrade package to PyPI
# with any tag starting with 't'
on:
  push:
    tags:
      - 't*'

# Create one single job
# that test publishes the package
# to PyPI using uv
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '^3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --dev

      - name: Build package
        run: uv build

      - name: Publish package to TestPyPI
        run: uv publish --publish-url https://test.pypi.org/legacy/
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Check for Successful Publication
        run: |
          version=$(grep -oP 'version = "\K[^"]+' pyproject.toml)
          echo "Checking if package gatorgrade version $version is available on TestPyPI..."
          sleep 10
          response=$(curl -s "https://test.pypi.org/pypi/gatorgrade/$version/json")
          if echo "$response" | grep -q "$version"; then
            echo "Package gatorgrade version $version is successfully published on TestPyPI."
          else
            echo "Package gatorgrade version $version was not found on TestPyPI."
            exit 1
          fi